### ISSUE TITLE
Argument Error in Distillation part of Image-to-Image translation notebook

### ISSUE THREAD

**Issue by Ashish-Abraham** [Snapchat/snapml-templates#12]
`NUM_EPOCHS = 50
!python distill.py --dataroot ./database/ukiyoe2photo \ --log_dir logs/cycle_gan/ukiyoe2photo/inception/student/2p6B \ --restore_teacher_G_path ukiyo_teacher_iter68000_net_G_B.pth \ --restore_pretrained_G_path ukiyo_teacher_iter68000_net_G_B.pth \ --restore_D_path ukiyo_teacher_iter68000_net_D_B.pth \ --real_stat_path ukiyo_A.npz \ --dataset_mode unaligned \ --distiller inception \ --gan_mode lsgan \ --nepochs NUM_EPOCHS --nepochs_decay NUM_EPOCHS \  --teacher_netG inception_9blocks --student_netG inception_9blocks \ --pretrained_ngf 64 --teacher_ngf 64 --student_ngf 20 \ --ndf 64 \ --num_threads 2 \ --eval_batch_size 2 \ --batch_size 10 \ --gpu_ids 0 \ --norm_affine \ --norm_affine_D \ --channels_reduction_factor 6 \ --kernel_sizes 1 3 5 \ --lambda_distill 2.8 \ --lambda_recon 1000 \ --prune_cin_lb 16 \ --target_flops 2.6e9 \ --distill_G_loss_type ka \ --netD multi_scale \ --crop_size 512,256 \ --preprocess resize_and_crop \ --load_size 600 \ --save_epoch_freq 1 \ --save_latest_freq 500 \ --direction BtoA \ --norm_student batch \ --padding_type_student zero \ --norm_affine_student \ --norm_track_running_stats_student \`

Cannot run the above code for distillation as it shows this error even if the variables are clearly defined in the code. I haven't changed anything in the given notebook.
![ss](https://user-images.githubusercontent.com/83216788/186171240-c1afc8d1-2d37-4ec6-b1da-cc2e45a04dde.png)

Any help regarding this is welcome.

**Comment by juhuSC** [comment]
Hi @Ashish-Abraham , thanks for reporting the issue, we have just merged the fix. Would you mind checking running the notebook again to see if your it is resolved before we close this issue.

**Comment by Ashish-Abraham** [comment]
`onnx_export.py: error: unrecognized arguments: \`

One more error in the onnx_export section

**Comment by juhuSC** [comment]
Looks like there is another trailing `\`, it should be fixed [here](https://github.com/Snapchat/snapml-templates/commit/eda4a16474fb42fba36bfc4b15bb0caba767268b)

**Comment by Ashish-Abraham** [comment]
Oh, I didn't notice that. Thanks a lot, now it works fine.
