### ISSUE TITLE
Issue Exporting YoloV7 model 

### ISSUE THREAD

**Issue by interactivetech** [Snapchat/snapml-templates#17]
Hi @juhuSC , great work on the Multi-Object Detection template! I am trying to export a `yolo-tiny.pt` model using the notebook, however when I import the converted `yolov7-tiny.onnx` into Lens Studio (v4.34.0) I get the following error:
```
23:27:03	Resource import for /Users/mendeza/Downloads/yolov7-tiny.onnx failed: ONNX model reshape layer converter does not support 5-D shape 
```

Here is the export command I run in google colab:
```
python export.py --weights yolov7-tiny.pt \
        --grid --simplify --export-snapml \
        --img-size 224 224 --max-wh 224
```

Let me know if you need additional information to debug!

**Comment by juhuSC** [comment]
Hi @interactivetech , thanks so much for trying out the template and raise the issue. Looks like it's taking a different path if we are exporting the original pre-trained model. I have fixed the issue in this [commit](https://github.com/ImEric/yolov7/commit/4a12407bc24b4ccc6f89f11e5c86cda19fcc28f6). There is nothing needs to be changed on your end. Would you mind pulling the repo and export the model again?

**Comment by interactivetech** [comment]
Thank you for the followup! The updated commit resolves the exporting issue! I have now modified the Multi-Object Detection Lens Studio example, and it incorporates the exported model. The bounding boxes look off with the default anchors in  ObjectDetectionController.js. Here is a link to the [lens studio project](https://s3.amazonaws.com/andrewmendez.me/files/Multi-Object+Detection+coco2.zip). Do I need to update/correct the anchors? If so, what is the best way to do this?

I attemtped to update the anchors by 1) printing the anchors using `torch.load(opt.weights)['model'].model[-1].anchor_grid.view(-1,2)` I get the following anchor results:
```
tensor([[ 10.,  13.],
        [ 16.,  30.],
        [ 33.,  23.],
        [ 30.,  61.],
        [ 62.,  45.],
        [ 59., 119.],
        [116.,  90.],
        [156., 198.],
        [373., 326.]], dtype=torch.float16)
```
Would these anchors work?
I also tried using the default yolov7-tiny anchors in [https://github.com/ImEric/yolov7/blob/55b90e111984dd85e7eed327e9ff271222aa8b82/cfg/training/yolov7-tiny.yaml#L7](https://github.com/ImEric/yolov7/blob/55b90e111984dd85e7eed327e9ff271222aa8b82/cfg/training/yolov7-tiny.yaml#L7 ) but that didnt seem to work also. 

Here is the link to the [un-exported model](https://s3.amazonaws.com/andrewmendez.me/files/yolov7-tiny-updated2.pt), and the exported [onnx file](https://s3.amazonaws.com/andrewmendez.me/files/yolov7-tiny-update2.onnx). Let me know if you need more information, thank you for your help!

**Comment by interactivetech** [comment]
I was able to resolve this issue! It turns out that the default anchor boxes work well when importing other model weights, such as yolo-tiny.onnx weights. The issue was in lens studio, when you add new classes (and colors for the classes),  do not use the default black color when using the Colored Rectangle Asset (to visualize object detection predictions). I use a different color, like red, shown in the screenshot via the yellow box. Now I can see all the detected boxes! Will close this issue, hopefully this will help other creators.
 
 <img width="1867" alt="Screen Shot 2022-12-06 at 12 54 41 PM" src="https://user-images.githubusercontent.com/5833510/205986580-ab663181-7bd0-4b91-90b7-4404ed7cb741.png">

**Comment by juhuSC** [comment]
Hi @interactivetech , glad the issue is already resolved. We will update our guide to remind users to update the color for boxes drawn
